--[[

│تم تطوير وبرمجة السورس من قبل جاك ✾ .
│@ PHP57
#-------------------------------------------------------------------
]]

local function jackkkka(msg,MsgText)
if msg.type ~= "pv" then
if MsgText[1] == "زخرفه" then
redis:setex(kalia..":jackkkkNow:"..msg.sender_user_id_,500,true)
sendMsg(msg.chat_id_,msg.id_,"| حسننا , الان يمكنك ارسال الاسم ولبعض الرموز المميزه اكتب رموز")    
return false
end

if redis:get(kalia..":jackkkkNow:"..msg.sender_user_id_) then
redis:del(kalia..":jackkkkNow:"..msg.sender_user_id_)
if utf8.len(msg.text) > 300 then
sendMsg(msg.chat_id_,msg.id_,"| لا يمكنك زخرفه اكثر من 20 حرف \n| ارسل امر زخرفه وحاول مجددا بحروف اقل")    
return false
elseif msg.text:match("\n") then
sendMsg(msg.chat_id_,msg.id_,"| لا يمكن زخرفه نص يحتوي على اكثر من سطر .")
return false
end
local EmojeS = {
' 𓁻',
' 𓏴  ',
' 𓏶 ',
' 𓏡',
' 𓏢', 
' 𓏣', 
' ☽‘',
' 𖠱²²', 
'▽', 
' 𖡛“', 
' 𖡚℡', 
' 𖡨', 
}

local Emoje = {
' ♕',
' 𖤍',
'˛𖤓',
' ཻ ☫',
' ♫ ',
' 𖠶 ',
' 𖠲',
' 𖡥',
'  ☬',
' 𖤐',
' 𓇼',
' ♘  '
}


local jackkkk = Text:gsub('ض','ضِٰـِۢ')
jackkkk = jackkkk:gsub('ص','صِٰـِۢ')
jackkkk = jackkkk:gsub('ث','ثِٰـِۢ')
jackkkk = jackkkk:gsub('ق','قِٰـِۢ')
jackkkk = jackkkk:gsub('ف','فِٰ͒ـِۢ')
jackkkk = jackkkk:gsub('غ','غِٰـِۢ')
jackkkk = jackkkk:gsub('ع','عِٰـِۢ')
jackkkk = jackkkk:gsub('خ','خِٰ̐ـِۢ')
jackkkk = jackkkk:gsub('ح','حِٰـِۢ')
jackkkk = jackkkk:gsub('ج','جِٰـِۢ')
jackkkk = jackkkk:gsub('ش','شِٰـِۢ')
jackkkk = jackkkk:gsub('س','سِٰـِۢ')
jackkkk = jackkkk:gsub('ي','يِٰـِۢ')
jackkkk = jackkkk:gsub('ب','بِٰـِۢ')
jackkkk = jackkkk:gsub('ل','لِٰـِۢ')
jackkkk = jackkkk:gsub('ا','آ')
jackkkk = jackkkk:gsub('ت','تِٰـِۢ')
jackkkk = jackkkk:gsub('ن','نِٰـِۢ')
jackkkk = jackkkk:gsub('م','مِٰـِۢ')
jackkkk = jackkkk:gsub('ك','ڪِٰـِۢ')
jackkkk = jackkkk:gsub('ط','طِٰـِۢ')
jackkkk = jackkkk:gsub('ظ','ظِٰـِۢ')
jackkkk = jackkkk:gsub('ء','ء')
jackkkk = jackkkk:gsub('ؤ','ؤ')
jackkkk = jackkkk:gsub('ر','ر')
jackkkk = jackkkk:gsub('ى','ى')
jackkkk = jackkkk:gsub('ز','ز')
jackkkk = jackkkk:gsub('و','ﯛ̲୭')
jackkkk = jackkkk:gsub('ه','ۿۿہ')
jackkkk = jackkkk:gsub('a','𝗮')
jackkkk = jackkkk:gsub('A','𝗔')
jackkkk = jackkkk:gsub("b","𝗯")
jackkkk = jackkkk:gsub("B","𝗕")
jackkkk = jackkkk:gsub("c","𝗰")
jackkkk = jackkkk:gsub("C","𝗖")
jackkkk = jackkkk:gsub("d","𝗱")
jackkkk = jackkkk:gsub("D","𝗗")
jackkkk = jackkkk:gsub("e","𝗲")
jackkkk = jackkkk:gsub("E","𝗘")
jackkkk = jackkkk:gsub("f","𝗳")
jackkkk = jackkkk:gsub("F","𝗙")
jackkkk = jackkkk:gsub("g","𝗴")
jackkkk = jackkkk:gsub("G","𝗚")
jackkkk = jackkkk:gsub("h","𝗵")
jackkkk = jackkkk:gsub("H","𝗛")
jackkkk = jackkkk:gsub("i","𝗹")
jackkkk = jackkkk:gsub("I","𝗜")
jackkkk = jackkkk:gsub("j","𝗝")
jackkkk = jackkkk:gsub("J","𝗝")
jackkkk = jackkkk:gsub("k","𝗸")
jackkkk = jackkkk:gsub("K","𝗞")
jackkkk = jackkkk:gsub("l","𝗹")
jackkkk = jackkkk:gsub("L","𝗟")
jackkkk = jackkkk:gsub("m","𝗺")
jackkkk = jackkkk:gsub("M","𝗠")
jackkkk = jackkkk:gsub("n","𝗻")
jackkkk = jackkkk:gsub("N","𝗡")
jackkkk = jackkkk:gsub("o","𝗼")
jackkkk = jackkkk:gsub("O","𝗢")
jackkkk = jackkkk:gsub("p","𝗽")
jackkkk = jackkkk:gsub("P","𝗣")
jackkkk = jackkkk:gsub("q","𝗾")
jackkkk = jackkkk:gsub("Q","𝗤")
jackkkk = jackkkk:gsub("r","𝗿")
jackkkk = jackkkk:gsub("R","𝗥")
jackkkk = jackkkk:gsub("s","𝘀")
jackkkk = jackkkk:gsub("S","𝗦")
jackkkk = jackkkk:gsub("t","𝘁")
jackkkk = jackkkk:gsub("T","𝗧")
jackkkk = jackkkk:gsub("u","𝘂")
jackkkk = jackkkk:gsub("U","𝗨")
jackkkk = jackkkk:gsub("v","𝘃")
jackkkk = jackkkk:gsub("V","𝗩")
jackkkk = jackkkk:gsub("w","𝘄")
jackkkk = jackkkk:gsub("W","𝗪")
jackkkk = jackkkk:gsub("x","𝘅")
jackkkk = jackkkk:gsub("X","𝗫")
jackkkk = jackkkk:gsub("y","𝘆")
jackkkk = jackkkk:gsub("Y","𝗬")
jackkkk = jackkkk:gsub("z","𝘇")
jackkkk = jackkkk:gsub("Z","𝗭")



local jackkkk2 = Text:gsub('ض','ضَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ص','صَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ث','ثَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ق','قَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ف','فَٰ͒ـُـٰٓ')
jackkkk2 = jackkkk2:gsub('غ','غَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ع','عَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('خ','خَٰ̐ـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ح','حَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ج','جَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ش','شَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('س','سَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ي','يَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ب','بَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ل','لَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ا','آ')
jackkkk2 = jackkkk2:gsub('ت','تَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ن','نَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('م','مَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ك','ڪَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ط','طَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ظ','ظَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ء','ء')
jackkkk2 = jackkkk2:gsub('ؤ','ؤ')
jackkkk2 = jackkkk2:gsub('ر','ر')
jackkkk2 = jackkkk2:gsub('ى','ى')
jackkkk2 = jackkkk2:gsub('ز','ز')
jackkkk2 = jackkkk2:gsub('و','ﯛ̲୭')
jackkkk2 = jackkkk2:gsub("ه", "ۿۿہ")
jackkkk2 = jackkkk2:gsub('a',"𝖆")
jackkkk2 = jackkkk2:gsub('A',"𝖆")
jackkkk2 = jackkkk2:gsub("b","𝖇")
jackkkk2 = jackkkk2:gsub("B","𝖇")
jackkkk2 = jackkkk2:gsub("c","𝖈")
jackkkk2 = jackkkk2:gsub("C","𝖈")
jackkkk2 = jackkkk2:gsub("d","𝖉")
jackkkk2 = jackkkk2:gsub("D","𝖉")
jackkkk2 = jackkkk2:gsub("e","𝖊")
jackkkk2 = jackkkk2:gsub("E","𝖊")
jackkkk2 = jackkkk2:gsub("f","𝖋")
jackkkk2 = jackkkk2:gsub("F","𝖋")
jackkkk2 = jackkkk2:gsub("g","𝖌")
jackkkk2 = jackkkk2:gsub("G","𝖌")
jackkkk2 = jackkkk2:gsub("h","𝖍")
jackkkk2 = jackkkk2:gsub("H","𝖍")
jackkkk2 = jackkkk2:gsub("i","𝖎")
jackkkk2 = jackkkk2:gsub("I","𝖎")
jackkkk2 = jackkkk2:gsub("j","𝖏")
jackkkk2 = jackkkk2:gsub("J","𝖏")
jackkkk2 = jackkkk2:gsub("k","𝖐")
jackkkk2 = jackkkk2:gsub("K","𝖐")
jackkkk2 = jackkkk2:gsub("l","𝖑")
jackkkk2 = jackkkk2:gsub("L","𝖑")
jackkkk2 = jackkkk2:gsub("m","𝖒")
jackkkk2 = jackkkk2:gsub("M","𝖒")
jackkkk2 = jackkkk2:gsub("n","𝖓")
jackkkk2 = jackkkk2:gsub("N","𝖓")
jackkkk2 = jackkkk2:gsub("o","𝖔")
jackkkk2 = jackkkk2:gsub("O","𝖔")
jackkkk2 = jackkkk2:gsub("p","𝖕")
jackkkk2 = jackkkk2:gsub("P","𝖕")
jackkkk2 = jackkkk2:gsub("q","𝖖")
jackkkk2 = jackkkk2:gsub("Q","𝖖")
jackkkk2 = jackkkk2:gsub("r","𝖗")
jackkkk2 = jackkkk2:gsub("R","𝖗")
jackkkk2 = jackkkk2:gsub("s","𝖘")
jackkkk2 = jackkkk2:gsub("S","𝖘")
jackkkk2 = jackkkk2:gsub("t","𝖙")
jackkkk2 = jackkkk2:gsub("T","𝖙")
jackkkk2 = jackkkk2:gsub("u","𝖚")
jackkkk2 = jackkkk2:gsub("U","𝖚")
jackkkk2 = jackkkk2:gsub("v","𝖛")
jackkkk2 = jackkkk2:gsub("V","𝖛")
jackkkk2 = jackkkk2:gsub("w","𝖜")
jackkkk2 = jackkkk2:gsub("W","𝖜")
jackkkk2 = jackkkk2:gsub("x","𝖝")
jackkkk2 = jackkkk2:gsub("X","𝖝")
jackkkk2 = jackkkk2:gsub("y","𝖞")
jackkkk2 = jackkkk2:gsub("Y","𝖞")
jackkkk2 = jackkkk2:gsub("z","𝖟")
jackkkk2 = jackkkk2:gsub("Z","𝖟")


local jackkkk3= Text:gsub('ض','ض')
jackkkk3= jackkkk3:gsub('ص','ص')
jackkkk3= jackkkk3:gsub('ث','ثہ')
jackkkk3= jackkkk3:gsub('ق','ق')
jackkkk3= jackkkk3:gsub('ف','فُہ')
jackkkk3= jackkkk3:gsub('غ','غہ')
jackkkk3= jackkkk3:gsub('ع','عہ')
jackkkk3= jackkkk3:gsub('ه','هٰہٰٖ')
jackkkk3= jackkkk3:gsub('خ','خہ')
jackkkk3= jackkkk3:gsub('ح','حہ')
jackkkk3= jackkkk3:gsub('ج','جہ')
jackkkk3= jackkkk3:gsub('د','د')
jackkkk3= jackkkk3:gsub('ذ','ذ')
jackkkk3= jackkkk3:gsub('ش','شہ')
jackkkk3= jackkkk3:gsub('س','سہ')
jackkkk3= jackkkk3:gsub('ي','يہ')
jackkkk3= jackkkk3:gsub('ب','بّ')
jackkkk3= jackkkk3:gsub('ل','لہ')
jackkkk3= jackkkk3:gsub('ا','ا')
jackkkk3= jackkkk3:gsub('ت','تہ')
jackkkk3= jackkkk3:gsub('ن','نٰہٰٖ')
jackkkk3= jackkkk3:gsub('م','مٰہٰٖ')
jackkkk3= jackkkk3:gsub('ك','كُہ')
jackkkk3= jackkkk3:gsub('ط','طہ')
jackkkk3= jackkkk3:gsub('ئ','ئ ْٰ')
jackkkk3= jackkkk3:gsub('ء','ء')
jackkkk3= jackkkk3:gsub('ؤ','ؤ')
jackkkk3= jackkkk3:gsub('ر','رَ')
jackkkk3= jackkkk3:gsub('لا','لہا')
jackkkk3= jackkkk3:gsub('ى','ىْ')
jackkkk3= jackkkk3:gsub('ة','ة')
jackkkk3= jackkkk3:gsub('و','و')
jackkkk3= jackkkk3:gsub('ز','ز')
jackkkk3= jackkkk3:gsub('ظ','ظۗہٰٰ')
jackkkk3= jackkkk3:gsub('q','𝐪')
jackkkk3= jackkkk3:gsub('Q','𝐪')
jackkkk3= jackkkk3:gsub('w','𝐰')
jackkkk3= jackkkk3:gsub('W','𝐰')
jackkkk3= jackkkk3:gsub('e','𝐞')
jackkkk3= jackkkk3:gsub('E','𝐞')
jackkkk3= jackkkk3:gsub('r','𝐫')
jackkkk3= jackkkk3:gsub('R','𝐫')
jackkkk3= jackkkk3:gsub('t','𝐭')
jackkkk3= jackkkk3:gsub('T','𝐭')
jackkkk3= jackkkk3:gsub('y','𝐲')
jackkkk3= jackkkk3:gsub('Y','𝐲')
jackkkk3= jackkkk3:gsub('u','𝐮')
jackkkk3= jackkkk3:gsub('i','𝐢')
jackkkk3= jackkkk3:gsub('o','𝐨')
jackkkk3= jackkkk3:gsub('p','𝐩')
jackkkk3= jackkkk3:gsub('a','𝐚')
jackkkk3= jackkkk3:gsub('s','𝐬')
jackkkk3= jackkkk3:gsub('d','𝐝')
jackkkk3= jackkkk3:gsub('f','𝐟')
jackkkk3= jackkkk3:gsub('g','𝐠')
jackkkk3= jackkkk3:gsub('h','𝐡')
jackkkk3= jackkkk3:gsub('j','𝐣')
jackkkk3= jackkkk3:gsub('k','𝐤')
jackkkk3= jackkkk3:gsub('U','𝐮')
jackkkk3= jackkkk3:gsub('I','𝐢')
jackkkk3= jackkkk3:gsub('O','𝐨')
jackkkk3= jackkkk3:gsub('P','𝐩')
jackkkk3= jackkkk3:gsub('A','𝐚')
jackkkk3= jackkkk3:gsub('S','𝐬')
jackkkk3= jackkkk3:gsub('D','𝐝')
jackkkk3= jackkkk3:gsub('F','𝐟')
jackkkk3= jackkkk3:gsub('G','𝐠')
jackkkk3= jackkkk3:gsub('H','𝐡')
jackkkk3= jackkkk3:gsub('J','𝐣')
jackkkk3= jackkkk3:gsub('K','𝐤')
jackkkk3= jackkkk3:gsub('L','𝐥')
jackkkk3= jackkkk3:gsub('l','𝐥')
jackkkk3= jackkkk3:gsub('z','𝐳')
jackkkk3= jackkkk3:gsub('Z','𝐳')
jackkkk3= jackkkk3:gsub('x','𝐱')
jackkkk3= jackkkk3:gsub('X','ẋ')
jackkkk3= jackkkk3:gsub('c','𝐜')
jackkkk3= jackkkk3:gsub('C','𝐜')
jackkkk3= jackkkk3:gsub('v','𝐯')
jackkkk3= jackkkk3:gsub('V','𝐯')
jackkkk3= jackkkk3:gsub('b','𝐛')
jackkkk3= jackkkk3:gsub('B','𝐛')
jackkkk3= jackkkk3:gsub('n','𝐧')
jackkkk3= jackkkk3:gsub('N','𝐧')
jackkkk3= jackkkk3:gsub('m','𝐦')
jackkkk3= jackkkk3:gsub('M','𝐦')


local jackkkk4= Text:gsub('ض','ضۜہٰٰ')
jackkkk4= jackkkk4:gsub('ص','ضۜہٰٰ')
jackkkk4= jackkkk4:gsub('ث','ثہٰٰ')
jackkkk4= jackkkk4:gsub('ق','قྀ̲ہٰٰ')
jackkkk4= jackkkk4:gsub('ف','ف͒ہٰٰ')
jackkkk4= jackkkk4:gsub('غ','غہٰٰ')
jackkkk4= jackkkk4:gsub('ع','عہٰٰ')
jackkkk4= jackkkk4:gsub('ه','هٰہٰٖ')
jackkkk4= jackkkk4:gsub('خ','خٰ̐ہ ')
jackkkk4= jackkkk4:gsub('ح','حہٰٰ')
jackkkk4= jackkkk4:gsub('ج','جـٰ̲ـہْۧ')
jackkkk4= jackkkk4:gsub('د','دٰ')
jackkkk4= jackkkk4:gsub('ذ','ذِٰ')
jackkkk4= jackkkk4:gsub('ش','شِٰہٰٰ')
jackkkk4= jackkkk4:gsub('س','سٰٓ')
jackkkk4= jackkkk4:gsub('ي','يِٰہ')
jackkkk4= jackkkk4:gsub('ب','بّہ')
jackkkk4= jackkkk4:gsub('ل','لـٰ̲ـہ')
jackkkk4= jackkkk4:gsub('ا','آ')
jackkkk4= jackkkk4:gsub('ت','تَہَٰ')
jackkkk4= jackkkk4:gsub('ن','نَِہ')
jackkkk4= jackkkk4:gsub('م','مٰ̲ہ')
jackkkk4= jackkkk4:gsub('ك','ڪٰྀہٰٰ')
jackkkk4= jackkkk4:gsub('ط','طۨہٰٰ')
jackkkk4= jackkkk4:gsub('ئ','ئ ْٰ')
jackkkk4= jackkkk4:gsub('ء','ء')
jackkkk4= jackkkk4:gsub('ؤ','ؤ')
jackkkk4= jackkkk4:gsub('ر','رَ')
jackkkk4= jackkkk4:gsub('لا','لہا')
jackkkk4= jackkkk4:gsub('ى','ىْ')
jackkkk4= jackkkk4:gsub('ة','ة')
jackkkk4= jackkkk4:gsub('و','وِٰ')
jackkkk4= jackkkk4:gsub('ز','زَٰ')
jackkkk4= jackkkk4:gsub('ظ','ظۗہٰٰ')
jackkkk4= jackkkk4:gsub('q','𝑸')
jackkkk4= jackkkk4:gsub('Q','𝑸')
jackkkk4= jackkkk4:gsub('w','𝑾')
jackkkk4= jackkkk4:gsub('W','𝑾')
jackkkk4= jackkkk4:gsub('e','𝑬')
jackkkk4= jackkkk4:gsub('E','𝑬')
jackkkk4= jackkkk4:gsub('r','𝑹')
jackkkk4= jackkkk4:gsub('R','𝑹')
jackkkk4= jackkkk4:gsub('t','𝑻')
jackkkk4= jackkkk4:gsub('T','𝑻')
jackkkk4= jackkkk4:gsub('y','𝒀')
jackkkk4= jackkkk4:gsub('Y','𝒀')
jackkkk4= jackkkk4:gsub('u','𝑼')
jackkkk4= jackkkk4:gsub('U','𝑼')
jackkkk4= jackkkk4:gsub('i','𝑰')
jackkkk4= jackkkk4:gsub('I','𝑰')
jackkkk4= jackkkk4:gsub('o','𝑶')
jackkkk4= jackkkk4:gsub('O','𝑶')
jackkkk4= jackkkk4:gsub('p','𝑷')
jackkkk4= jackkkk4:gsub('P','𝑷')
jackkkk4= jackkkk4:gsub('a','𝑨')
jackkkk4= jackkkk4:gsub('A','𝑨')
jackkkk4= jackkkk4:gsub('s','𝑺')
jackkkk4= jackkkk4:gsub('S','𝑺')
jackkkk4= jackkkk4:gsub('d','𝑫')
jackkkk4= jackkkk4:gsub('D','𝑫')
jackkkk4= jackkkk4:gsub('f','𝑭')
jackkkk4= jackkkk4:gsub('F','𝑭')
jackkkk4= jackkkk4:gsub('g','𝑮')
jackkkk4= jackkkk4:gsub('G','𝑮')
jackkkk4= jackkkk4:gsub('h','𝑯')
jackkkk4= jackkkk4:gsub('H','𝑯')
jackkkk4= jackkkk4:gsub('j','𝑱')
jackkkk4= jackkkk4:gsub('J','𝑱')
jackkkk4= jackkkk4:gsub('k','𝑲')
jackkkk4= jackkkk4:gsub('K','𝑲')
jackkkk4= jackkkk4:gsub('l','𝑳')
jackkkk4= jackkkk4:gsub('L','𝑳')
jackkkk4= jackkkk4:gsub('z','𝒁')
jackkkk4= jackkkk4:gsub('Z','𝒁')
jackkkk4= jackkkk4:gsub('x','𝑿')
jackkkk4= jackkkk4:gsub('X','𝑿')
jackkkk4= jackkkk4:gsub('c','𝑪')
jackkkk4= jackkkk4:gsub('C','𝑪')
jackkkk4= jackkkk4:gsub('v','𝑽')
jackkkk4= jackkkk4:gsub('V','𝑽')
jackkkk4= jackkkk4:gsub('b','𝑩')
jackkkk4= jackkkk4:gsub('B','𝑩')
jackkkk4= jackkkk4:gsub('n','𝑵')
jackkkk4= jackkkk4:gsub('N','𝑵')
jackkkk4= jackkkk4:gsub('m','𝑴')
jackkkk4= jackkkk4:gsub('M','𝑴')



local jackkkk5= Text:gsub('ض','ضَ')
jackkkk5= jackkkk5:gsub('ص','صً')
jackkkk5= jackkkk5:gsub('ث','ثَ')
jackkkk5= jackkkk5:gsub('ق','قُ')
jackkkk5= jackkkk5:gsub('ف','فّ')
jackkkk5= jackkkk5:gsub('غ','غِ')
jackkkk5= jackkkk5:gsub('ع','عُ')
jackkkk5= jackkkk5:gsub('ه','ﮭ')
jackkkk5= jackkkk5:gsub('خ','خِ')
jackkkk5= jackkkk5:gsub('ح','حٌ')
jackkkk5= jackkkk5:gsub('ج','جُ')
jackkkk5= jackkkk5:gsub('د','دِ')
jackkkk5= jackkkk5:gsub('ذ','ذَ')
jackkkk5= jackkkk5:gsub('ش','شِ')
jackkkk5= jackkkk5:gsub('س','سً')
jackkkk5= jackkkk5:gsub('ي','يْ')
jackkkk5= jackkkk5:gsub('ب','بّ')
jackkkk5= jackkkk5:gsub('ل','لَ')
jackkkk5= jackkkk5:gsub('ا','أُ')
jackkkk5= jackkkk5:gsub('ت','تٌ')
jackkkk5= jackkkk5:gsub('ن','نً')
jackkkk5= jackkkk5:gsub('م','مِ')
jackkkk5= jackkkk5:gsub('ك','ڳّ')
jackkkk5= jackkkk5:gsub('ط','طٌ')
jackkkk5= jackkkk5:gsub('ئ','ئ')
jackkkk5= jackkkk5:gsub('ء','ء')
jackkkk5= jackkkk5:gsub('ؤ','ؤ')
jackkkk5= jackkkk5:gsub('ر','رٌ')
jackkkk5= jackkkk5:gsub('لا','لٌأً')
jackkkk5= jackkkk5:gsub('ى','ى')
jackkkk5= jackkkk5:gsub('ة','ةَ')
jackkkk5= jackkkk5:gsub('و','وِ')
jackkkk5= jackkkk5:gsub('ز','زُ')
jackkkk5= jackkkk5:gsub('ظ','ظ')
jackkkk5= jackkkk5:gsub('q','𝒒')
jackkkk5= jackkkk5:gsub('Q','𝒒')
jackkkk5= jackkkk5:gsub('w','𝒘')
jackkkk5= jackkkk5:gsub('W','𝒘')
jackkkk5= jackkkk5:gsub('e','𝒆')
jackkkk5= jackkkk5:gsub('E','𝒆')
jackkkk5= jackkkk5:gsub('r','𝒓')
jackkkk5= jackkkk5:gsub('R','𝒓')
jackkkk5= jackkkk5:gsub('t','𝒕')
jackkkk5= jackkkk5:gsub('T','𝒕')
jackkkk5= jackkkk5:gsub('y','𝒚')
jackkkk5= jackkkk5:gsub('Y','𝒚')
jackkkk5= jackkkk5:gsub('u','𝒖')
jackkkk5= jackkkk5:gsub('U','𝒖')
jackkkk5= jackkkk5:gsub('i','𝒊')
jackkkk5= jackkkk5:gsub('I','𝒊')
jackkkk5= jackkkk5:gsub('o','𝒐')
jackkkk5= jackkkk5:gsub('O','𝒐')
jackkkk5= jackkkk5:gsub('p','𝒑')
jackkkk5= jackkkk5:gsub('P','𝒑')
jackkkk5= jackkkk5:gsub('a','𝒂')
jackkkk5= jackkkk5:gsub('A','𝒂')
jackkkk5= jackkkk5:gsub('s','𝒔')
jackkkk5= jackkkk5:gsub('S','𝒔')
jackkkk5= jackkkk5:gsub('d','𝒅')
jackkkk5= jackkkk5:gsub('D','𝒅')
jackkkk5= jackkkk5:gsub('f','𝒇')
jackkkk5= jackkkk5:gsub('F','𝒇')
jackkkk5= jackkkk5:gsub('g','𝒈')
jackkkk5= jackkkk5:gsub('G','𝒈')
jackkkk5= jackkkk5:gsub('h','𝒉')
jackkkk5= jackkkk5:gsub('H','𝒉')
jackkkk5= jackkkk5:gsub('j','𝒋')
jackkkk5= jackkkk5:gsub('J','𝒋')
jackkkk5= jackkkk5:gsub('K','𝒌')
jackkkk5= jackkkk5:gsub('k','𝒌')
jackkkk5= jackkkk5:gsub('L','𝒍')
jackkkk5= jackkkk5:gsub('l','𝒍')
jackkkk5= jackkkk5:gsub('z','𝒛')
jackkkk5= jackkkk5:gsub('Z','𝒛')
jackkkk5= jackkkk5:gsub('x','𝒙')
jackkkk5= jackkkk5:gsub('X','𝒙')
jackkkk5= jackkkk5:gsub('c','𝒄')
jackkkk5= jackkkk5:gsub('C','𝒄')
jackkkk5= jackkkk5:gsub('v','𝒗')
jackkkk5= jackkkk5:gsub('V','𝒗')
jackkkk5= jackkkk5:gsub('b','𝒃')
jackkkk5= jackkkk5:gsub('B','𝒃')
jackkkk5= jackkkk5:gsub('n','𝒏')
jackkkk5= jackkkk5:gsub('N','𝒏')
jackkkk5= jackkkk5:gsub('m','𝒎')
jackkkk5= jackkkk5:gsub('M','𝒎')



local jackkkk6= Text:gsub('ض','ﺿ̭͠')
jackkkk6= jackkkk6:gsub('ص','ﺻ͡')
jackkkk6= jackkkk6:gsub('ث','ﺜ̲')
jackkkk6= jackkkk6:gsub('ق','ﭰ')
jackkkk6= jackkkk6:gsub('ف','ﻓ̲')
jackkkk6= jackkkk6:gsub('غ','ﻏ̲')
jackkkk6= jackkkk6:gsub('ع','ﻌ̲')
jackkkk6= jackkkk6:gsub('ه','ﮬ̲̌')
jackkkk6= jackkkk6:gsub('خ','خٌ')
jackkkk6= jackkkk6:gsub('ح','ﺣ̅')
jackkkk6= jackkkk6:gsub('ج','جُ')
jackkkk6= jackkkk6:gsub('د','ډ̝')
jackkkk6= jackkkk6:gsub('ذ','ذً')
jackkkk6= jackkkk6:gsub('ش','ﺷ̲')
jackkkk6= jackkkk6:gsub('س','ﺳ̉')
jackkkk6= jackkkk6:gsub('ي','ﯾ̃̐')
jackkkk6= jackkkk6:gsub('ب','ﺑ̲')
jackkkk6= jackkkk6:gsub('ل','ا̄ﻟ')
jackkkk6= jackkkk6:gsub('ا','ﺈ̃')
jackkkk6= jackkkk6:gsub('ت','ټُ')
jackkkk6= jackkkk6:gsub('ن','ﻧ̲')
jackkkk6= jackkkk6:gsub('م','ﻣ̲̉')
jackkkk6= jackkkk6:gsub('ك','گ')
jackkkk6= jackkkk6:gsub('ط','ﻁ̲')
jackkkk6= jackkkk6:gsub('ئ',' ْٰئ')
jackkkk6= jackkkk6:gsub('ء','ء')
jackkkk6= jackkkk6:gsub('ؤ','ؤ')
jackkkk6= jackkkk6:gsub('ر','ہڕ')
jackkkk6= jackkkk6:gsub('لا','ﻟ̲ﺂ̲')
jackkkk6= jackkkk6:gsub('ى','ى')
jackkkk6= jackkkk6:gsub('ة','ة')
jackkkk6= jackkkk6:gsub('و','ۇۈۉ')
jackkkk6= jackkkk6:gsub('ز','زُ')
jackkkk6= jackkkk6:gsub('ظ','ﻇ̲')
jackkkk6= jackkkk6:gsub('q','ǫ')
jackkkk6= jackkkk6:gsub('Q','ǫ')
jackkkk6= jackkkk6:gsub('w','ᴡ')
jackkkk6= jackkkk6:gsub('W','ᴡ')
jackkkk6= jackkkk6:gsub('e','ᴇ')
jackkkk6= jackkkk6:gsub('E','ᴇ')
jackkkk6= jackkkk6:gsub('r','ʀ')
jackkkk6= jackkkk6:gsub('R','ʀ')
jackkkk6= jackkkk6:gsub('t','ᴛ')
jackkkk6= jackkkk6:gsub('T','ᴛ')
jackkkk6= jackkkk6:gsub('y','ʏ')
jackkkk6= jackkkk6:gsub('Y','ʏ')
jackkkk6= jackkkk6:gsub('u','ụ')
jackkkk6= jackkkk6:gsub('U','ụ')
jackkkk6= jackkkk6:gsub('i','ɪ')
jackkkk6= jackkkk6:gsub('I','ɪ')
jackkkk6= jackkkk6:gsub('o','ᴏ')
jackkkk6= jackkkk6:gsub('O','ᴏ')
jackkkk6= jackkkk6:gsub('p','ᴘ')
jackkkk6= jackkkk6:gsub('P','ᴘ')
jackkkk6= jackkkk6:gsub('a','ᴀ')
jackkkk6= jackkkk6:gsub('A','ᴀ')
jackkkk6= jackkkk6:gsub('s','ѕ')
jackkkk6= jackkkk6:gsub('S','ѕ')
jackkkk6= jackkkk6:gsub('d','ᴅ')
jackkkk6= jackkkk6:gsub('D','ᴅ')
jackkkk6= jackkkk6:gsub('f','ғ')
jackkkk6= jackkkk6:gsub('F','ғ')
jackkkk6= jackkkk6:gsub('g','ɢ')
jackkkk6= jackkkk6:gsub('G','ɢ')
jackkkk6= jackkkk6:gsub('h','ʜ')
jackkkk6= jackkkk6:gsub('H','ʜ')
jackkkk6= jackkkk6:gsub('j','ᴊ')
jackkkk6= jackkkk6:gsub('J','ᴊ')
jackkkk6= jackkkk6:gsub('K','ᴋ')
jackkkk6= jackkkk6:gsub('k','ᴋ')
jackkkk6= jackkkk6:gsub('L','ʟ')
jackkkk6= jackkkk6:gsub('l','ʟ')
jackkkk6= jackkkk6:gsub('z','ᴢ')
jackkkk6= jackkkk6:gsub('Z','ᴢ')
jackkkk6= jackkkk6:gsub('x','х')
jackkkk6= jackkkk6:gsub('X','х')
jackkkk6= jackkkk6:gsub('c','ᴄ')
jackkkk6= jackkkk6:gsub('C','ᴄ')
jackkkk6= jackkkk6:gsub('v','ᴠ')
jackkkk6= jackkkk6:gsub('V','ᴠ')
jackkkk6= jackkkk6:gsub('b','ʙ')
jackkkk6= jackkkk6:gsub('B','ʙ')
jackkkk6= jackkkk6:gsub('n','ɴ')
jackkkk6= jackkkk6:gsub('N','ɴ')
jackkkk6= jackkkk6:gsub('m','ᴍ')
jackkkk6= jackkkk6:gsub('M','ᴍ')



local jackkkk7= Text:gsub('ض','ﺿ')
jackkkk7= jackkkk7:gsub('ص','ﺻ')
jackkkk7= jackkkk7:gsub('ث','ﭥ')
jackkkk7= jackkkk7:gsub('ق','ﻗ̮ـ̃')
jackkkk7= jackkkk7:gsub('ف','ﭬ')
jackkkk7= jackkkk7:gsub('غ','ﻏ̣̐')
jackkkk7= jackkkk7:gsub('ع','ﻋ')
jackkkk7= jackkkk7:gsub('ه','ھَہّ')
jackkkk7= jackkkk7:gsub('خ','ﺧ')
jackkkk7= jackkkk7:gsub('ح','פ')
jackkkk7= jackkkk7:gsub('ج','ﭴ')
jackkkk7= jackkkk7:gsub('د','ﮃ')
jackkkk7= jackkkk7:gsub('ذ','ذ')
jackkkk7= jackkkk7:gsub('ش','ﺷ')
jackkkk7= jackkkk7:gsub('س','ﺳ')
jackkkk7= jackkkk7:gsub('ي','ﯾ')
jackkkk7= jackkkk7:gsub('ب','ﺑ')
jackkkk7= jackkkk7:gsub('ل','ﻟ')
jackkkk7= jackkkk7:gsub('ا','ﺂ')
jackkkk7= jackkkk7:gsub('ت','ﭠ')
jackkkk7= jackkkk7:gsub('ن','ﻧ')
jackkkk7= jackkkk7:gsub('م','ﻣ̝̚')
jackkkk7= jackkkk7:gsub('ك','گـ')
jackkkk7= jackkkk7:gsub('ط','ﻁْ')
jackkkk7= jackkkk7:gsub('ئ','ٰئـ')
jackkkk7= jackkkk7:gsub('ء','ء')
jackkkk7= jackkkk7:gsub('ؤ','ﯗ')
jackkkk7= jackkkk7:gsub('ر','ړُ')
jackkkk7= jackkkk7:gsub('لا','ﻟآ')
jackkkk7= jackkkk7:gsub('ى','ـﮯ')
jackkkk7= jackkkk7:gsub('ة','ة')
jackkkk7= jackkkk7:gsub('و','ۆ')
jackkkk7= jackkkk7:gsub('ز','ژ')
jackkkk7= jackkkk7:gsub('ظ','ﻅ')
jackkkk7= jackkkk7:gsub('q','𝘘')
jackkkk7= jackkkk7:gsub('Q','𝘘')
jackkkk7= jackkkk7:gsub('w','𝘞')
jackkkk7= jackkkk7:gsub('W','𝘞')
jackkkk7= jackkkk7:gsub('e','𝘌')
jackkkk7= jackkkk7:gsub('E','𝘌')
jackkkk7= jackkkk7:gsub('r','𝘙')
jackkkk7= jackkkk7:gsub('R','𝘙')
jackkkk7= jackkkk7:gsub('t','𝘛')
jackkkk7= jackkkk7:gsub('T','𝘛')
jackkkk7= jackkkk7:gsub('y','𝘠')
jackkkk7= jackkkk7:gsub('Y','𝘠')
jackkkk7= jackkkk7:gsub('u','𝘜')
jackkkk7= jackkkk7:gsub('U','𝘜')
jackkkk7= jackkkk7:gsub('i','𝘐')
jackkkk7= jackkkk7:gsub('I','𝘐')
jackkkk7= jackkkk7:gsub('o','𝘖')
jackkkk7= jackkkk7:gsub('O','𝘖')
jackkkk7= jackkkk7:gsub('p','𝘗')
jackkkk7= jackkkk7:gsub('P','𝘗')
jackkkk7= jackkkk7:gsub('a','𝘈')
jackkkk7= jackkkk7:gsub('A','𝘈')
jackkkk7= jackkkk7:gsub('s','𝘚')
jackkkk7= jackkkk7:gsub('S','𝘚')
jackkkk7= jackkkk7:gsub('d','𝘋')
jackkkk7= jackkkk7:gsub('D','𝘋')
jackkkk7= jackkkk7:gsub('f','𝘍')
jackkkk7= jackkkk7:gsub('F','𝘍')
jackkkk7= jackkkk7:gsub('g','𝘎')
jackkkk7= jackkkk7:gsub('G','𝘎')
jackkkk7= jackkkk7:gsub('h','𝘏')
jackkkk7= jackkkk7:gsub('H','𝘏')
jackkkk7= jackkkk7:gsub('j','𝘑')
jackkkk7= jackkkk7:gsub('J','𝘑')
jackkkk7= jackkkk7:gsub('k','𝘒')
jackkkk7= jackkkk7:gsub('K','𝘒')
jackkkk7= jackkkk7:gsub('L','𝘓')
jackkkk7= jackkkk7:gsub('l','𝘓')
jackkkk7= jackkkk7:gsub('z','𝘡')
jackkkk7= jackkkk7:gsub('Z','𝘡')
jackkkk7= jackkkk7:gsub('x','𝘟')
jackkkk7= jackkkk7:gsub('X','𝘟')
jackkkk7= jackkkk7:gsub('c','𝘊')
jackkkk7= jackkkk7:gsub('C','𝘊')
jackkkk7= jackkkk7:gsub('v','𝘝')
jackkkk7= jackkkk7:gsub('V','𝘝')
jackkkk7= jackkkk7:gsub('b','𝘉')
jackkkk7= jackkkk7:gsub('B','𝘉')
jackkkk7= jackkkk7:gsub('n','𝘕')
jackkkk7= jackkkk7:gsub('N','𝘕')
jackkkk7= jackkkk7:gsub('m','𝘔')
jackkkk7= jackkkk7:gsub('M','𝘔')



local jackkkk8= Text:gsub('ض','ض');
jackkkk8= jackkkk8:gsub('ص','صہٰ')
jackkkk8= jackkkk8:gsub('ث','ثہٰـ')
jackkkk8= jackkkk8:gsub('ق','قہٰ')
jackkkk8= jackkkk8:gsub('ف','فہٰ')
jackkkk8= jackkkk8:gsub('غ','غـْ')
jackkkk8= jackkkk8:gsub('ع','ع')
jackkkk8= jackkkk8:gsub('ه','هٰہٰٖ')
jackkkk8= jackkkk8:gsub('خ','خخَـ')
jackkkk8= jackkkk8:gsub('ح','حہٰ')
jackkkk8= jackkkk8:gsub('ج','ججہٰ')
jackkkk8= jackkkk8:gsub('د','دَ')
jackkkk8= jackkkk8:gsub('ذ','ذّ')
jackkkk8= jackkkk8:gsub('ش','ششہٰ')
jackkkk8= jackkkk8:gsub('س','سہٰ')
jackkkk8= jackkkk8:gsub('ي','يٰ')
jackkkk8= jackkkk8:gsub('ب','بٰٰ')
jackkkk8= jackkkk8:gsub('ل','لہٰ')
jackkkk8= jackkkk8:gsub('ا','آ')
jackkkk8= jackkkk8:gsub('ت','تہٰ')
jackkkk8= jackkkk8:gsub('ن','نہٰ')
jackkkk8= jackkkk8:gsub('م','مہٰ')
jackkkk8= jackkkk8:gsub('ك','ككہٰ')
jackkkk8= jackkkk8:gsub('ط','طہٰ')
jackkkk8= jackkkk8:gsub('ئ',' ْئٰ')
jackkkk8= jackkkk8:gsub('ء','ء')
jackkkk8= jackkkk8:gsub('ؤ','ؤؤَ')
jackkkk8= jackkkk8:gsub('ر','رَ')
jackkkk8= jackkkk8:gsub('لا','لہٰا')
jackkkk8= jackkkk8:gsub('ى','ىہٰ')
jackkkk8= jackkkk8:gsub('ة','ة')
jackkkk8= jackkkk8:gsub('و','ہٰو')
jackkkk8= jackkkk8:gsub('ز','ز')
jackkkk8= jackkkk8:gsub('ظ','ظہٰ')
jackkkk8= jackkkk8:gsub('q','𝚀')
jackkkk8= jackkkk8:gsub('Q','𝚀')
jackkkk8= jackkkk8:gsub('w','𝚆')
jackkkk8= jackkkk8:gsub('W','𝚆')
jackkkk8= jackkkk8:gsub('e','𝙴')
jackkkk8= jackkkk8:gsub('E','𝙴')
jackkkk8= jackkkk8:gsub('r','𝚁')
jackkkk8= jackkkk8:gsub('R','𝚁')
jackkkk8= jackkkk8:gsub('t','𝚃')
jackkkk8= jackkkk8:gsub('T','𝚃')
jackkkk8= jackkkk8:gsub('y','𝚈')
jackkkk8= jackkkk8:gsub('Y','𝚈')
jackkkk8= jackkkk8:gsub('u','𝚄')
jackkkk8= jackkkk8:gsub('U','𝚄')
jackkkk8= jackkkk8:gsub('i','𝙸')
jackkkk8= jackkkk8:gsub('I','𝙸')
jackkkk8= jackkkk8:gsub('o','𝙾')
jackkkk8= jackkkk8:gsub('O','𝙾')
jackkkk8= jackkkk8:gsub('p','𝙿')
jackkkk8= jackkkk8:gsub('P','𝙿')
jackkkk8= jackkkk8:gsub('a','𝙰')
jackkkk8= jackkkk8:gsub('A','𝙰')
jackkkk8= jackkkk8:gsub('s','𝚂')
jackkkk8= jackkkk8:gsub('S','𝚂')
jackkkk8= jackkkk8:gsub('d','𝙳')
jackkkk8= jackkkk8:gsub('D','𝙳')
jackkkk8= jackkkk8:gsub('f','𝙵')
jackkkk8= jackkkk8:gsub('F','𝙵')
jackkkk8= jackkkk8:gsub('g','𝙶')
jackkkk8= jackkkk8:gsub('G','𝙶')
jackkkk8= jackkkk8:gsub('h','𝙷')
jackkkk8= jackkkk8:gsub('H','𝙷')
jackkkk8= jackkkk8:gsub('j','𝙹')
jackkkk8= jackkkk8:gsub('J','𝙹')
jackkkk8= jackkkk8:gsub('k','𝙺')
jackkkk8= jackkkk8:gsub('K','𝙺')
jackkkk8= jackkkk8:gsub('L','𝙻')
jackkkk8= jackkkk8:gsub('l','𝙻')
jackkkk8= jackkkk8:gsub('z','𝚉')
jackkkk8= jackkkk8:gsub('Z','𝚉')
jackkkk8= jackkkk8:gsub('x','𝚇')
jackkkk8= jackkkk8:gsub('X','𝚇')
jackkkk8= jackkkk8:gsub('c','𝙲')
jackkkk8= jackkkk8:gsub('C','𝙲')
jackkkk8= jackkkk8:gsub('v','𝚅')
jackkkk8= jackkkk8:gsub('V','𝚅')
jackkkk8= jackkkk8:gsub('b','𝙱')
jackkkk8= jackkkk8:gsub('B','𝙱')
jackkkk8= jackkkk8:gsub('n','𝙽')
jackkkk8= jackkkk8:gsub('N','𝙽')
jackkkk8= jackkkk8:gsub('m','𝙼')
jackkkk8= jackkkk8:gsub('M','𝙼')



local jackkkk9= Text:gsub('ض','ض')
jackkkk9= jackkkk9:gsub('ص','ص')
jackkkk9= jackkkk9:gsub('ث','ث')
jackkkk9= jackkkk9:gsub('ق','قٌ')
jackkkk9= jackkkk9:gsub('ف','فُ')
jackkkk9= jackkkk9:gsub('غ','غ')
jackkkk9= jackkkk9:gsub('ع','عٍ')
jackkkk9= jackkkk9:gsub('ه','هـ')
jackkkk9= jackkkk9:gsub('خ','خـ')
jackkkk9= jackkkk9:gsub('ح','حٍ')
jackkkk9= jackkkk9:gsub('ج','جٍ')
jackkkk9= jackkkk9:gsub('د','دِ')
jackkkk9= jackkkk9:gsub('ذ','ذَ')
jackkkk9= jackkkk9:gsub('ش','شُ')
jackkkk9= jackkkk9:gsub('س','س')
jackkkk9= jackkkk9:gsub('ي','ي')
jackkkk9= jackkkk9:gsub('ب','بَ')
jackkkk9= jackkkk9:gsub('ل','لُِ')
jackkkk9= jackkkk9:gsub('ا','آ')
jackkkk9= jackkkk9:gsub('ت','ت')
jackkkk9= jackkkk9:gsub('ن','ن')
jackkkk9= jackkkk9:gsub('م','م')
jackkkk9= jackkkk9:gsub('ك','ڪ')
jackkkk9= jackkkk9:gsub('ط','طُ')
jackkkk9= jackkkk9:gsub('ئ','ئ ْٰ')
jackkkk9= jackkkk9:gsub('ء','ء')
jackkkk9= jackkkk9:gsub('ؤ','ؤ')
jackkkk9= jackkkk9:gsub('ر','ر')
jackkkk9= jackkkk9:gsub('لا','لُِآ')
jackkkk9= jackkkk9:gsub('ى','ىْ')
jackkkk9= jackkkk9:gsub('ة','ة')
jackkkk9= jackkkk9:gsub('و','وو')
jackkkk9= jackkkk9:gsub('ز','ز')
jackkkk9= jackkkk9:gsub('ظ','ظهُ')
jackkkk9= jackkkk9:gsub('q','ℚ')
jackkkk9= jackkkk9:gsub('Q','ℚ')
jackkkk9= jackkkk9:gsub('w','𝕎')
jackkkk9= jackkkk9:gsub('W','𝕎')
jackkkk9= jackkkk9:gsub('e','𝔼')
jackkkk9= jackkkk9:gsub('E','𝔼')
jackkkk9= jackkkk9:gsub('r','ℝ')
jackkkk9= jackkkk9:gsub('R','ℝ')
jackkkk9= jackkkk9:gsub('t','𝕋')
jackkkk9= jackkkk9:gsub('T','𝕋')
jackkkk9= jackkkk9:gsub('y','𝕐')
jackkkk9= jackkkk9:gsub('Y','𝕐')
jackkkk9= jackkkk9:gsub('u','𝕌')
jackkkk9= jackkkk9:gsub('U','𝕌')
jackkkk9= jackkkk9:gsub('i','𝕀')
jackkkk9= jackkkk9:gsub('I','𝕀')
jackkkk9= jackkkk9:gsub('o','𝕆')
jackkkk9= jackkkk9:gsub('O','𝕆')
jackkkk9= jackkkk9:gsub('p','ℙ')
jackkkk9= jackkkk9:gsub('P','ℙ')
jackkkk9= jackkkk9:gsub('a','𝔸')
jackkkk9= jackkkk9:gsub('A','𝔸')
jackkkk9= jackkkk9:gsub('s','𝕊')
jackkkk9= jackkkk9:gsub('S','𝕊')
jackkkk9= jackkkk9:gsub('d','𝔻')
jackkkk9= jackkkk9:gsub('D','𝔻')
jackkkk9= jackkkk9:gsub('f','𝔽')
jackkkk9= jackkkk9:gsub('F','𝔽')
jackkkk9= jackkkk9:gsub('g','𝔾')
jackkkk9= jackkkk9:gsub('G','𝔾')
jackkkk9= jackkkk9:gsub('h','ℍ')
jackkkk9= jackkkk9:gsub('H','ℍ')
jackkkk9= jackkkk9:gsub('j','𝕁')
jackkkk9= jackkkk9:gsub('J','𝕁')
jackkkk9= jackkkk9:gsub('k','𝕂')
jackkkk9= jackkkk9:gsub('K','𝕂')
jackkkk9= jackkkk9:gsub('L','𝕃')
jackkkk9= jackkkk9:gsub('l','𝕃')
jackkkk9= jackkkk9:gsub('z','ℤ')
jackkkk9= jackkkk9:gsub('Z','ℤ')
jackkkk9= jackkkk9:gsub('x','𝕏')
jackkkk9= jackkkk9:gsub('X','𝕏')
jackkkk9= jackkkk9:gsub('c','ℂ')
jackkkk9= jackkkk9:gsub('C','ℂ')
jackkkk9= jackkkk9:gsub('v','𝕍')
jackkkk9= jackkkk9:gsub('V','𝕍')
jackkkk9= jackkkk9:gsub('b','𝔹')
jackkkk9= jackkkk9:gsub('B','𝔹')
jackkkk9= jackkkk9:gsub('n','ℕ')
jackkkk9= jackkkk9:gsub('N','ℕ')
jackkkk9= jackkkk9:gsub('m','𝕄')
jackkkk9= jackkkk9:gsub('M','𝕄')


local Text_jackkkka = "1- `"..jackkkk..EmojeS[math.random(#EmojeS)]
.."`\n\n2- `"..jackkkk2..EmojeS[math.random(#EmojeS)]
.."`\n\n3- `"..jackkkk3..EmojeS[math.random(#EmojeS)]
.."`\n\n4- `"..jackkkk4..EmojeS[math.random(#EmojeS)]
.."`\n\n5- `"..jackkkk5..EmojeS[math.random(#EmojeS)]
.."`\n\n6- `"..jackkkk6..EmojeS[math.random(#EmojeS)]
.."`\n\n7- `"..jackkkk7..EmojeS[math.random(#EmojeS)]
.."`\n\n8- `"..jackkkk8..Emoje[math.random(#Emoje)]
.."`\n\n9- `"..jackkkk9..Emoje[math.random(#Emoje)]
.."`\n\n10- `"..jackkkk5..Emoje[math.random(#Emoje)]
Text_jackkkka = Text_jackkkka.."`\n\n اضغط علـي الاسـم ليـتم النـسخ \n★"
sendMsg(msg.chat_id_,msg.id_,Text_jackkkka)
return false
end
end

end
local function TextRes(msg)

if msg.text and msg.type ~= "pv" and redis:get(kalia..":jackkkkNow:"..msg.sender_user_id_) then
Text = msg.text
redis:del(kalia..":jackkkkNow:"..msg.sender_user_id_)
if utf8.len(msg.text) > 300 then
sendMsg(msg.chat_id_,msg.id_," لا يمكنك زخرفه اكثر من 300 حرف \n  ارسل امر زخرفه وحاول مجددا بحروف اقل")    
return false
end
local EmojeS = {
' 𓁻',
' 𓏴  ',
' 𓏶 ',
' 𓏡',
' 𓏢', 
' 𓏣', 
' ☽‘',
' 𖠱²²', 
'▽', 
' 𖡛“', 
' 𖡚℡', 
' 𖡨', 
}

local Emoje = {
' ♕',
' 𖤍',
'˛𖤓',
' ཻ ☫',
' ♫ ',
' 𖠶 ',
' 𖠲',
' 𖡥',
'  ☬',
' 𖤐',
' 𓇼',
' ♘  '
}


local jackkkk = Text:gsub('ض','ضِٰـِۢ')
jackkkk = jackkkk:gsub('ص','صِٰـِۢ')
jackkkk = jackkkk:gsub('ث','ثِٰـِۢ')
jackkkk = jackkkk:gsub('ق','قِٰـِۢ')
jackkkk = jackkkk:gsub('ف','فِٰ͒ـِۢ')
jackkkk = jackkkk:gsub('غ','غِٰـِۢ')
jackkkk = jackkkk:gsub('ع','عِٰـِۢ')
jackkkk = jackkkk:gsub('خ','خِٰ̐ـِۢ')
jackkkk = jackkkk:gsub('ح','حِٰـِۢ')
jackkkk = jackkkk:gsub('ج','جِٰـِۢ')
jackkkk = jackkkk:gsub('ش','شِٰـِۢ')
jackkkk = jackkkk:gsub('س','سِٰـِۢ')
jackkkk = jackkkk:gsub('ي','يِٰـِۢ')
jackkkk = jackkkk:gsub('ب','بِٰـِۢ')
jackkkk = jackkkk:gsub('ل','لِٰـِۢ')
jackkkk = jackkkk:gsub('ا','آ')
jackkkk = jackkkk:gsub('ت','تِٰـِۢ')
jackkkk = jackkkk:gsub('ن','نِٰـِۢ')
jackkkk = jackkkk:gsub('م','مِٰـِۢ')
jackkkk = jackkkk:gsub('ك','ڪِٰـِۢ')
jackkkk = jackkkk:gsub('ط','طِٰـِۢ')
jackkkk = jackkkk:gsub('ظ','ظِٰـِۢ')
jackkkk = jackkkk:gsub('ء','ء')
jackkkk = jackkkk:gsub('ؤ','ؤ')
jackkkk = jackkkk:gsub('ر','ر')
jackkkk = jackkkk:gsub('ى','ى')
jackkkk = jackkkk:gsub('ز','ز')
jackkkk = jackkkk:gsub('و','ﯛ̲୭')
jackkkk = jackkkk:gsub('ه','ۿۿہ')
jackkkk = jackkkk:gsub('a','𝗮')
jackkkk = jackkkk:gsub('A','𝗔')
jackkkk = jackkkk:gsub("b","𝗯")
jackkkk = jackkkk:gsub("B","𝗕")
jackkkk = jackkkk:gsub("c","𝗰")
jackkkk = jackkkk:gsub("C","𝗖")
jackkkk = jackkkk:gsub("d","𝗱")
jackkkk = jackkkk:gsub("D","𝗗")
jackkkk = jackkkk:gsub("e","𝗲")
jackkkk = jackkkk:gsub("E","𝗘")
jackkkk = jackkkk:gsub("f","𝗳")
jackkkk = jackkkk:gsub("F","𝗙")
jackkkk = jackkkk:gsub("g","𝗴")
jackkkk = jackkkk:gsub("G","𝗚")
jackkkk = jackkkk:gsub("h","𝗵")
jackkkk = jackkkk:gsub("H","𝗛")
jackkkk = jackkkk:gsub("i","𝗹")
jackkkk = jackkkk:gsub("I","𝗜")
jackkkk = jackkkk:gsub("j","𝗝")
jackkkk = jackkkk:gsub("J","𝗝")
jackkkk = jackkkk:gsub("k","𝗸")
jackkkk = jackkkk:gsub("K","𝗞")
jackkkk = jackkkk:gsub("l","𝗹")
jackkkk = jackkkk:gsub("L","𝗟")
jackkkk = jackkkk:gsub("m","𝗺")
jackkkk = jackkkk:gsub("M","𝗠")
jackkkk = jackkkk:gsub("n","𝗻")
jackkkk = jackkkk:gsub("N","𝗡")
jackkkk = jackkkk:gsub("o","𝗼")
jackkkk = jackkkk:gsub("O","𝗢")
jackkkk = jackkkk:gsub("p","𝗽")
jackkkk = jackkkk:gsub("P","𝗣")
jackkkk = jackkkk:gsub("q","𝗾")
jackkkk = jackkkk:gsub("Q","𝗤")
jackkkk = jackkkk:gsub("r","𝗿")
jackkkk = jackkkk:gsub("R","𝗥")
jackkkk = jackkkk:gsub("s","𝘀")
jackkkk = jackkkk:gsub("S","𝗦")
jackkkk = jackkkk:gsub("t","𝘁")
jackkkk = jackkkk:gsub("T","𝗧")
jackkkk = jackkkk:gsub("u","𝘂")
jackkkk = jackkkk:gsub("U","𝗨")
jackkkk = jackkkk:gsub("v","𝘃")
jackkkk = jackkkk:gsub("V","𝗩")
jackkkk = jackkkk:gsub("w","𝘄")
jackkkk = jackkkk:gsub("W","𝗪")
jackkkk = jackkkk:gsub("x","𝘅")
jackkkk = jackkkk:gsub("X","𝗫")
jackkkk = jackkkk:gsub("y","𝘆")
jackkkk = jackkkk:gsub("Y","𝗬")
jackkkk = jackkkk:gsub("z","𝘇")
jackkkk = jackkkk:gsub("Z","𝗭")



local jackkkk2 = Text:gsub('ض','ضَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ص','صَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ث','ثَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ق','قَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ف','فَٰ͒ـُـٰٓ')
jackkkk2 = jackkkk2:gsub('غ','غَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ع','عَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('خ','خَٰ̐ـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ح','حَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ج','جَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ش','شَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('س','سَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ي','يَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ب','بَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ل','لَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ا','آ')
jackkkk2 = jackkkk2:gsub('ت','تَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ن','نَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('م','مَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ك','ڪَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ط','طَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ظ','ظَٰـُـٰٓ')
jackkkk2 = jackkkk2:gsub('ء','ء')
jackkkk2 = jackkkk2:gsub('ؤ','ؤ')
jackkkk2 = jackkkk2:gsub('ر','ر')
jackkkk2 = jackkkk2:gsub('ى','ى')
jackkkk2 = jackkkk2:gsub('ز','ز')
jackkkk2 = jackkkk2:gsub('و','ﯛ̲୭')
jackkkk2 = jackkkk2:gsub("ه", "ۿۿہ")
jackkkk2 = jackkkk2:gsub('a',"𝖆")
jackkkk2 = jackkkk2:gsub('A',"𝖆")
jackkkk2 = jackkkk2:gsub("b","𝖇")
jackkkk2 = jackkkk2:gsub("B","𝖇")
jackkkk2 = jackkkk2:gsub("c","𝖈")
jackkkk2 = jackkkk2:gsub("C","𝖈")
jackkkk2 = jackkkk2:gsub("d","𝖉")
jackkkk2 = jackkkk2:gsub("D","𝖉")
jackkkk2 = jackkkk2:gsub("e","𝖊")
jackkkk2 = jackkkk2:gsub("E","𝖊")
jackkkk2 = jackkkk2:gsub("f","𝖋")
jackkkk2 = jackkkk2:gsub("F","𝖋")
jackkkk2 = jackkkk2:gsub("g","𝖌")
jackkkk2 = jackkkk2:gsub("G","𝖌")
jackkkk2 = jackkkk2:gsub("h","𝖍")
jackkkk2 = jackkkk2:gsub("H","𝖍")
jackkkk2 = jackkkk2:gsub("i","𝖎")
jackkkk2 = jackkkk2:gsub("I","𝖎")
jackkkk2 = jackkkk2:gsub("j","𝖏")
jackkkk2 = jackkkk2:gsub("J","𝖏")
jackkkk2 = jackkkk2:gsub("k","𝖐")
jackkkk2 = jackkkk2:gsub("K","𝖐")
jackkkk2 = jackkkk2:gsub("l","𝖑")
jackkkk2 = jackkkk2:gsub("L","𝖑")
jackkkk2 = jackkkk2:gsub("m","𝖒")
jackkkk2 = jackkkk2:gsub("M","𝖒")
jackkkk2 = jackkkk2:gsub("n","𝖓")
jackkkk2 = jackkkk2:gsub("N","𝖓")
jackkkk2 = jackkkk2:gsub("o","𝖔")
jackkkk2 = jackkkk2:gsub("O","𝖔")
jackkkk2 = jackkkk2:gsub("p","𝖕")
jackkkk2 = jackkkk2:gsub("P","𝖕")
jackkkk2 = jackkkk2:gsub("q","𝖖")
jackkkk2 = jackkkk2:gsub("Q","𝖖")
jackkkk2 = jackkkk2:gsub("r","𝖗")
jackkkk2 = jackkkk2:gsub("R","𝖗")
jackkkk2 = jackkkk2:gsub("s","𝖘")
jackkkk2 = jackkkk2:gsub("S","𝖘")
jackkkk2 = jackkkk2:gsub("t","𝖙")
jackkkk2 = jackkkk2:gsub("T","𝖙")
jackkkk2 = jackkkk2:gsub("u","𝖚")
jackkkk2 = jackkkk2:gsub("U","𝖚")
jackkkk2 = jackkkk2:gsub("v","𝖛")
jackkkk2 = jackkkk2:gsub("V","𝖛")
jackkkk2 = jackkkk2:gsub("w","𝖜")
jackkkk2 = jackkkk2:gsub("W","𝖜")
jackkkk2 = jackkkk2:gsub("x","𝖝")
jackkkk2 = jackkkk2:gsub("X","𝖝")
jackkkk2 = jackkkk2:gsub("y","𝖞")
jackkkk2 = jackkkk2:gsub("Y","𝖞")
jackkkk2 = jackkkk2:gsub("z","𝖟")
jackkkk2 = jackkkk2:gsub("Z","𝖟")


local jackkkk3= Text:gsub('ض','ض')
jackkkk3= jackkkk3:gsub('ص','ص')
jackkkk3= jackkkk3:gsub('ث','ثہ')
jackkkk3= jackkkk3:gsub('ق','ق')
jackkkk3= jackkkk3:gsub('ف','فُہ')
jackkkk3= jackkkk3:gsub('غ','غہ')
jackkkk3= jackkkk3:gsub('ع','عہ')
jackkkk3= jackkkk3:gsub('ه','هٰہٰٖ')
jackkkk3= jackkkk3:gsub('خ','خہ')
jackkkk3= jackkkk3:gsub('ح','حہ')
jackkkk3= jackkkk3:gsub('ج','جہ')
jackkkk3= jackkkk3:gsub('د','د')
jackkkk3= jackkkk3:gsub('ذ','ذ')
jackkkk3= jackkkk3:gsub('ش','شہ')
jackkkk3= jackkkk3:gsub('س','سہ')
jackkkk3= jackkkk3:gsub('ي','يہ')
jackkkk3= jackkkk3:gsub('ب','بّ')
jackkkk3= jackkkk3:gsub('ل','لہ')
jackkkk3= jackkkk3:gsub('ا','ا')
jackkkk3= jackkkk3:gsub('ت','تہ')
jackkkk3= jackkkk3:gsub('ن','نٰہٰٖ')
jackkkk3= jackkkk3:gsub('م','مٰہٰٖ')
jackkkk3= jackkkk3:gsub('ك','كُہ')
jackkkk3= jackkkk3:gsub('ط','طہ')
jackkkk3= jackkkk3:gsub('ئ','ئ ْٰ')
jackkkk3= jackkkk3:gsub('ء','ء')
jackkkk3= jackkkk3:gsub('ؤ','ؤ')
jackkkk3= jackkkk3:gsub('ر','رَ')
jackkkk3= jackkkk3:gsub('لا','لہا')
jackkkk3= jackkkk3:gsub('ى','ىْ')
jackkkk3= jackkkk3:gsub('ة','ة')
jackkkk3= jackkkk3:gsub('و','و')
jackkkk3= jackkkk3:gsub('ز','ز')
jackkkk3= jackkkk3:gsub('ظ','ظۗہٰٰ')
jackkkk3= jackkkk3:gsub('q','𝐪')
jackkkk3= jackkkk3:gsub('Q','𝐪')
jackkkk3= jackkkk3:gsub('w','𝐰')
jackkkk3= jackkkk3:gsub('W','𝐰')
jackkkk3= jackkkk3:gsub('e','𝐞')
jackkkk3= jackkkk3:gsub('E','𝐞')
jackkkk3= jackkkk3:gsub('r','𝐫')
jackkkk3= jackkkk3:gsub('R','𝐫')
jackkkk3= jackkkk3:gsub('t','𝐭')
jackkkk3= jackkkk3:gsub('T','𝐭')
jackkkk3= jackkkk3:gsub('y','𝐲')
jackkkk3= jackkkk3:gsub('Y','𝐲')
jackkkk3= jackkkk3:gsub('u','𝐮')
jackkkk3= jackkkk3:gsub('i','𝐢')
jackkkk3= jackkkk3:gsub('o','𝐨')
jackkkk3= jackkkk3:gsub('p','𝐩')
jackkkk3= jackkkk3:gsub('a','𝐚')
jackkkk3= jackkkk3:gsub('s','𝐬')
jackkkk3= jackkkk3:gsub('d','𝐝')
jackkkk3= jackkkk3:gsub('f','𝐟')
jackkkk3= jackkkk3:gsub('g','𝐠')
jackkkk3= jackkkk3:gsub('h','𝐡')
jackkkk3= jackkkk3:gsub('j','𝐣')
jackkkk3= jackkkk3:gsub('k','𝐤')
jackkkk3= jackkkk3:gsub('U','𝐮')
jackkkk3= jackkkk3:gsub('I','𝐢')
jackkkk3= jackkkk3:gsub('O','𝐨')
jackkkk3= jackkkk3:gsub('P','𝐩')
jackkkk3= jackkkk3:gsub('A','𝐚')
jackkkk3= jackkkk3:gsub('S','𝐬')
jackkkk3= jackkkk3:gsub('D','𝐝')
jackkkk3= jackkkk3:gsub('F','𝐟')
jackkkk3= jackkkk3:gsub('G','𝐠')
jackkkk3= jackkkk3:gsub('H','𝐡')
jackkkk3= jackkkk3:gsub('J','𝐣')
jackkkk3= jackkkk3:gsub('K','𝐤')
jackkkk3= jackkkk3:gsub('L','𝐥')
jackkkk3= jackkkk3:gsub('l','𝐥')
jackkkk3= jackkkk3:gsub('z','𝐳')
jackkkk3= jackkkk3:gsub('Z','𝐳')
jackkkk3= jackkkk3:gsub('x','𝐱')
jackkkk3= jackkkk3:gsub('X','ẋ')
jackkkk3= jackkkk3:gsub('c','𝐜')
jackkkk3= jackkkk3:gsub('C','𝐜')
jackkkk3= jackkkk3:gsub('v','𝐯')
jackkkk3= jackkkk3:gsub('V','𝐯')
jackkkk3= jackkkk3:gsub('b','𝐛')
jackkkk3= jackkkk3:gsub('B','𝐛')
jackkkk3= jackkkk3:gsub('n','𝐧')
jackkkk3= jackkkk3:gsub('N','𝐧')
jackkkk3= jackkkk3:gsub('m','𝐦')
jackkkk3= jackkkk3:gsub('M','𝐦')


local jackkkk4= Text:gsub('ض','ضۜہٰٰ')
jackkkk4= jackkkk4:gsub('ص','ضۜہٰٰ')
jackkkk4= jackkkk4:gsub('ث','ثہٰٰ')
jackkkk4= jackkkk4:gsub('ق','قྀ̲ہٰٰ')
jackkkk4= jackkkk4:gsub('ف','ف͒ہٰٰ')
jackkkk4= jackkkk4:gsub('غ','غہٰٰ')
jackkkk4= jackkkk4:gsub('ع','عہٰٰ')
jackkkk4= jackkkk4:gsub('ه','هٰہٰٖ')
jackkkk4= jackkkk4:gsub('خ','خٰ̐ہ ')
jackkkk4= jackkkk4:gsub('ح','حہٰٰ')
jackkkk4= jackkkk4:gsub('ج','جـٰ̲ـہْۧ')
jackkkk4= jackkkk4:gsub('د','دٰ')
jackkkk4= jackkkk4:gsub('ذ','ذِٰ')
jackkkk4= jackkkk4:gsub('ش','شِٰہٰٰ')
jackkkk4= jackkkk4:gsub('س','سٰٓ')
jackkkk4= jackkkk4:gsub('ي','يِٰہ')
jackkkk4= jackkkk4:gsub('ب','بّہ')
jackkkk4= jackkkk4:gsub('ل','لـٰ̲ـہ')
jackkkk4= jackkkk4:gsub('ا','آ')
jackkkk4= jackkkk4:gsub('ت','تَہَٰ')
jackkkk4= jackkkk4:gsub('ن','نَِہ')
jackkkk4= jackkkk4:gsub('م','مٰ̲ہ')
jackkkk4= jackkkk4:gsub('ك','ڪٰྀہٰٰ')
jackkkk4= jackkkk4:gsub('ط','طۨہٰٰ')
jackkkk4= jackkkk4:gsub('ئ','ئ ْٰ')
jackkkk4= jackkkk4:gsub('ء','ء')
jackkkk4= jackkkk4:gsub('ؤ','ؤ')
jackkkk4= jackkkk4:gsub('ر','رَ')
jackkkk4= jackkkk4:gsub('لا','لہا')
jackkkk4= jackkkk4:gsub('ى','ىْ')
jackkkk4= jackkkk4:gsub('ة','ة')
jackkkk4= jackkkk4:gsub('و','وِٰ')
jackkkk4= jackkkk4:gsub('ز','زَٰ')
jackkkk4= jackkkk4:gsub('ظ','ظۗہٰٰ')
jackkkk4= jackkkk4:gsub('q','𝑸')
jackkkk4= jackkkk4:gsub('Q','𝑸')
jackkkk4= jackkkk4:gsub('w','𝑾')
jackkkk4= jackkkk4:gsub('W','𝑾')
jackkkk4= jackkkk4:gsub('e','𝑬')
jackkkk4= jackkkk4:gsub('E','𝑬')
jackkkk4= jackkkk4:gsub('r','𝑹')
jackkkk4= jackkkk4:gsub('R','𝑹')
jackkkk4= jackkkk4:gsub('t','𝑻')
jackkkk4= jackkkk4:gsub('T','𝑻')
jackkkk4= jackkkk4:gsub('y','𝒀')
jackkkk4= jackkkk4:gsub('Y','𝒀')
jackkkk4= jackkkk4:gsub('u','𝑼')
jackkkk4= jackkkk4:gsub('U','𝑼')
jackkkk4= jackkkk4:gsub('i','𝑰')
jackkkk4= jackkkk4:gsub('I','𝑰')
jackkkk4= jackkkk4:gsub('o','𝑶')
jackkkk4= jackkkk4:gsub('O','𝑶')
jackkkk4= jackkkk4:gsub('p','𝑷')
jackkkk4= jackkkk4:gsub('P','𝑷')
jackkkk4= jackkkk4:gsub('a','𝑨')
jackkkk4= jackkkk4:gsub('A','𝑨')
jackkkk4= jackkkk4:gsub('s','𝑺')
jackkkk4= jackkkk4:gsub('S','𝑺')
jackkkk4= jackkkk4:gsub('d','𝑫')
jackkkk4= jackkkk4:gsub('D','𝑫')
jackkkk4= jackkkk4:gsub('f','𝑭')
jackkkk4= jackkkk4:gsub('F','𝑭')
jackkkk4= jackkkk4:gsub('g','𝑮')
jackkkk4= jackkkk4:gsub('G','𝑮')
jackkkk4= jackkkk4:gsub('h','𝑯')
jackkkk4= jackkkk4:gsub('H','𝑯')
jackkkk4= jackkkk4:gsub('j','𝑱')
jackkkk4= jackkkk4:gsub('J','𝑱')
jackkkk4= jackkkk4:gsub('k','𝑲')
jackkkk4= jackkkk4:gsub('K','𝑲')
jackkkk4= jackkkk4:gsub('l','𝑳')
jackkkk4= jackkkk4:gsub('L','𝑳')
jackkkk4= jackkkk4:gsub('z','𝒁')
jackkkk4= jackkkk4:gsub('Z','𝒁')
jackkkk4= jackkkk4:gsub('x','𝑿')
jackkkk4= jackkkk4:gsub('X','𝑿')
jackkkk4= jackkkk4:gsub('c','𝑪')
jackkkk4= jackkkk4:gsub('C','𝑪')
jackkkk4= jackkkk4:gsub('v','𝑽')
jackkkk4= jackkkk4:gsub('V','𝑽')
jackkkk4= jackkkk4:gsub('b','𝑩')
jackkkk4= jackkkk4:gsub('B','𝑩')
jackkkk4= jackkkk4:gsub('n','𝑵')
jackkkk4= jackkkk4:gsub('N','𝑵')
jackkkk4= jackkkk4:gsub('m','𝑴')
jackkkk4= jackkkk4:gsub('M','𝑴')



local jackkkk5= Text:gsub('ض','ضَ')
jackkkk5= jackkkk5:gsub('ص','صً')
jackkkk5= jackkkk5:gsub('ث','ثَ')
jackkkk5= jackkkk5:gsub('ق','قُ')
jackkkk5= jackkkk5:gsub('ف','فّ')
jackkkk5= jackkkk5:gsub('غ','غِ')
jackkkk5= jackkkk5:gsub('ع','عُ')
jackkkk5= jackkkk5:gsub('ه','ﮭ')
jackkkk5= jackkkk5:gsub('خ','خِ')
jackkkk5= jackkkk5:gsub('ح','حٌ')
jackkkk5= jackkkk5:gsub('ج','جُ')
jackkkk5= jackkkk5:gsub('د','دِ')
jackkkk5= jackkkk5:gsub('ذ','ذَ')
jackkkk5= jackkkk5:gsub('ش','شِ')
jackkkk5= jackkkk5:gsub('س','سً')
jackkkk5= jackkkk5:gsub('ي','يْ')
jackkkk5= jackkkk5:gsub('ب','بّ')
jackkkk5= jackkkk5:gsub('ل','لَ')
jackkkk5= jackkkk5:gsub('ا','أُ')
jackkkk5= jackkkk5:gsub('ت','تٌ')
jackkkk5= jackkkk5:gsub('ن','نً')
jackkkk5= jackkkk5:gsub('م','مِ')
jackkkk5= jackkkk5:gsub('ك','ڳّ')
jackkkk5= jackkkk5:gsub('ط','طٌ')
jackkkk5= jackkkk5:gsub('ئ','ئ')
jackkkk5= jackkkk5:gsub('ء','ء')
jackkkk5= jackkkk5:gsub('ؤ','ؤ')
jackkkk5= jackkkk5:gsub('ر','رٌ')
jackkkk5= jackkkk5:gsub('لا','لٌأً')
jackkkk5= jackkkk5:gsub('ى','ى')
jackkkk5= jackkkk5:gsub('ة','ةَ')
jackkkk5= jackkkk5:gsub('و','وِ')
jackkkk5= jackkkk5:gsub('ز','زُ')
jackkkk5= jackkkk5:gsub('ظ','ظ')
jackkkk5= jackkkk5:gsub('q','𝒒')
jackkkk5= jackkkk5:gsub('Q','𝒒')
jackkkk5= jackkkk5:gsub('w','𝒘')
jackkkk5= jackkkk5:gsub('W','𝒘')
jackkkk5= jackkkk5:gsub('e','𝒆')
jackkkk5= jackkkk5:gsub('E','𝒆')
jackkkk5= jackkkk5:gsub('r','𝒓')
jackkkk5= jackkkk5:gsub('R','𝒓')
jackkkk5= jackkkk5:gsub('t','𝒕')
jackkkk5= jackkkk5:gsub('T','𝒕')
jackkkk5= jackkkk5:gsub('y','𝒚')
jackkkk5= jackkkk5:gsub('Y','𝒚')
jackkkk5= jackkkk5:gsub('u','𝒖')
jackkkk5= jackkkk5:gsub('U','𝒖')
jackkkk5= jackkkk5:gsub('i','𝒊')
jackkkk5= jackkkk5:gsub('I','𝒊')
jackkkk5= jackkkk5:gsub('o','𝒐')
jackkkk5= jackkkk5:gsub('O','𝒐')
jackkkk5= jackkkk5:gsub('p','𝒑')
jackkkk5= jackkkk5:gsub('P','𝒑')
jackkkk5= jackkkk5:gsub('a','𝒂')
jackkkk5= jackkkk5:gsub('A','𝒂')
jackkkk5= jackkkk5:gsub('s','𝒔')
jackkkk5= jackkkk5:gsub('S','𝒔')
jackkkk5= jackkkk5:gsub('d','𝒅')
jackkkk5= jackkkk5:gsub('D','𝒅')
jackkkk5= jackkkk5:gsub('f','𝒇')
jackkkk5= jackkkk5:gsub('F','𝒇')
jackkkk5= jackkkk5:gsub('g','𝒈')
jackkkk5= jackkkk5:gsub('G','𝒈')
jackkkk5= jackkkk5:gsub('h','𝒉')
jackkkk5= jackkkk5:gsub('H','𝒉')
jackkkk5= jackkkk5:gsub('j','𝒋')
jackkkk5= jackkkk5:gsub('J','𝒋')
jackkkk5= jackkkk5:gsub('K','𝒌')
jackkkk5= jackkkk5:gsub('k','𝒌')
jackkkk5= jackkkk5:gsub('L','𝒍')
jackkkk5= jackkkk5:gsub('l','𝒍')
jackkkk5= jackkkk5:gsub('z','𝒛')
jackkkk5= jackkkk5:gsub('Z','𝒛')
jackkkk5= jackkkk5:gsub('x','𝒙')
jackkkk5= jackkkk5:gsub('X','𝒙')
jackkkk5= jackkkk5:gsub('c','𝒄')
jackkkk5= jackkkk5:gsub('C','𝒄')
jackkkk5= jackkkk5:gsub('v','𝒗')
jackkkk5= jackkkk5:gsub('V','𝒗')
jackkkk5= jackkkk5:gsub('b','𝒃')
jackkkk5= jackkkk5:gsub('B','𝒃')
jackkkk5= jackkkk5:gsub('n','𝒏')
jackkkk5= jackkkk5:gsub('N','𝒏')
jackkkk5= jackkkk5:gsub('m','𝒎')
jackkkk5= jackkkk5:gsub('M','𝒎')



local jackkkk6= Text:gsub('ض','ﺿ̭͠')
jackkkk6= jackkkk6:gsub('ص','ﺻ͡')
jackkkk6= jackkkk6:gsub('ث','ﺜ̲')
jackkkk6= jackkkk6:gsub('ق','ﭰ')
jackkkk6= jackkkk6:gsub('ف','ﻓ̲')
jackkkk6= jackkkk6:gsub('غ','ﻏ̲')
jackkkk6= jackkkk6:gsub('ع','ﻌ̲')
jackkkk6= jackkkk6:gsub('ه','ﮬ̲̌')
jackkkk6= jackkkk6:gsub('خ','خٌ')
jackkkk6= jackkkk6:gsub('ح','ﺣ̅')
jackkkk6= jackkkk6:gsub('ج','جُ')
jackkkk6= jackkkk6:gsub('د','ډ̝')
jackkkk6= jackkkk6:gsub('ذ','ذً')
jackkkk6= jackkkk6:gsub('ش','ﺷ̲')
jackkkk6= jackkkk6:gsub('س','ﺳ̉')
jackkkk6= jackkkk6:gsub('ي','ﯾ̃̐')
jackkkk6= jackkkk6:gsub('ب','ﺑ̲')
jackkkk6= jackkkk6:gsub('ل','ا̄ﻟ')
jackkkk6= jackkkk6:gsub('ا','ﺈ̃')
jackkkk6= jackkkk6:gsub('ت','ټُ')
jackkkk6= jackkkk6:gsub('ن','ﻧ̲')
jackkkk6= jackkkk6:gsub('م','ﻣ̲̉')
jackkkk6= jackkkk6:gsub('ك','گ')
jackkkk6= jackkkk6:gsub('ط','ﻁ̲')
jackkkk6= jackkkk6:gsub('ئ',' ْٰئ')
jackkkk6= jackkkk6:gsub('ء','ء')
jackkkk6= jackkkk6:gsub('ؤ','ؤ')
jackkkk6= jackkkk6:gsub('ر','ہڕ')
jackkkk6= jackkkk6:gsub('لا','ﻟ̲ﺂ̲')
jackkkk6= jackkkk6:gsub('ى','ى')
jackkkk6= jackkkk6:gsub('ة','ة')
jackkkk6= jackkkk6:gsub('و','ۇۈۉ')
jackkkk6= jackkkk6:gsub('ز','زُ')
jackkkk6= jackkkk6:gsub('ظ','ﻇ̲')
jackkkk6= jackkkk6:gsub('q','ǫ')
jackkkk6= jackkkk6:gsub('Q','ǫ')
jackkkk6= jackkkk6:gsub('w','ᴡ')
jackkkk6= jackkkk6:gsub('W','ᴡ')
jackkkk6= jackkkk6:gsub('e','ᴇ')
jackkkk6= jackkkk6:gsub('E','ᴇ')
jackkkk6= jackkkk6:gsub('r','ʀ')
jackkkk6= jackkkk6:gsub('R','ʀ')
jackkkk6= jackkkk6:gsub('t','ᴛ')
jackkkk6= jackkkk6:gsub('T','ᴛ')
jackkkk6= jackkkk6:gsub('y','ʏ')
jackkkk6= jackkkk6:gsub('Y','ʏ')
jackkkk6= jackkkk6:gsub('u','ụ')
jackkkk6= jackkkk6:gsub('U','ụ')
jackkkk6= jackkkk6:gsub('i','ɪ')
jackkkk6= jackkkk6:gsub('I','ɪ')
jackkkk6= jackkkk6:gsub('o','ᴏ')
jackkkk6= jackkkk6:gsub('O','ᴏ')
jackkkk6= jackkkk6:gsub('p','ᴘ')
jackkkk6= jackkkk6:gsub('P','ᴘ')
jackkkk6= jackkkk6:gsub('a','ᴀ')
jackkkk6= jackkkk6:gsub('A','ᴀ')
jackkkk6= jackkkk6:gsub('s','ѕ')
jackkkk6= jackkkk6:gsub('S','ѕ')
jackkkk6= jackkkk6:gsub('d','ᴅ')
jackkkk6= jackkkk6:gsub('D','ᴅ')
jackkkk6= jackkkk6:gsub('f','ғ')
jackkkk6= jackkkk6:gsub('F','ғ')
jackkkk6= jackkkk6:gsub('g','ɢ')
jackkkk6= jackkkk6:gsub('G','ɢ')
jackkkk6= jackkkk6:gsub('h','ʜ')
jackkkk6= jackkkk6:gsub('H','ʜ')
jackkkk6= jackkkk6:gsub('j','ᴊ')
jackkkk6= jackkkk6:gsub('J','ᴊ')
jackkkk6= jackkkk6:gsub('K','ᴋ')
jackkkk6= jackkkk6:gsub('k','ᴋ')
jackkkk6= jackkkk6:gsub('L','ʟ')
jackkkk6= jackkkk6:gsub('l','ʟ')
jackkkk6= jackkkk6:gsub('z','ᴢ')
jackkkk6= jackkkk6:gsub('Z','ᴢ')
jackkkk6= jackkkk6:gsub('x','х')
jackkkk6= jackkkk6:gsub('X','х')
jackkkk6= jackkkk6:gsub('c','ᴄ')
jackkkk6= jackkkk6:gsub('C','ᴄ')
jackkkk6= jackkkk6:gsub('v','ᴠ')
jackkkk6= jackkkk6:gsub('V','ᴠ')
jackkkk6= jackkkk6:gsub('b','ʙ')
jackkkk6= jackkkk6:gsub('B','ʙ')
jackkkk6= jackkkk6:gsub('n','ɴ')
jackkkk6= jackkkk6:gsub('N','ɴ')
jackkkk6= jackkkk6:gsub('m','ᴍ')
jackkkk6= jackkkk6:gsub('M','ᴍ')



local jackkkk7= Text:gsub('ض','ﺿ')
jackkkk7= jackkkk7:gsub('ص','ﺻ')
jackkkk7= jackkkk7:gsub('ث','ﭥ')
jackkkk7= jackkkk7:gsub('ق','ﻗ̮ـ̃')
jackkkk7= jackkkk7:gsub('ف','ﭬ')
jackkkk7= jackkkk7:gsub('غ','ﻏ̣̐')
jackkkk7= jackkkk7:gsub('ع','ﻋ')
jackkkk7= jackkkk7:gsub('ه','ھَہّ')
jackkkk7= jackkkk7:gsub('خ','ﺧ')
jackkkk7= jackkkk7:gsub('ح','פ')
jackkkk7= jackkkk7:gsub('ج','ﭴ')
jackkkk7= jackkkk7:gsub('د','ﮃ')
jackkkk7= jackkkk7:gsub('ذ','ذ')
jackkkk7= jackkkk7:gsub('ش','ﺷ')
jackkkk7= jackkkk7:gsub('س','ﺳ')
jackkkk7= jackkkk7:gsub('ي','ﯾ')
jackkkk7= jackkkk7:gsub('ب','ﺑ')
jackkkk7= jackkkk7:gsub('ل','ﻟ')
jackkkk7= jackkkk7:gsub('ا','ﺂ')
jackkkk7= jackkkk7:gsub('ت','ﭠ')
jackkkk7= jackkkk7:gsub('ن','ﻧ')
jackkkk7= jackkkk7:gsub('م','ﻣ̝̚')
jackkkk7= jackkkk7:gsub('ك','گـ')
jackkkk7= jackkkk7:gsub('ط','ﻁْ')
jackkkk7= jackkkk7:gsub('ئ','ٰئـ')
jackkkk7= jackkkk7:gsub('ء','ء')
jackkkk7= jackkkk7:gsub('ؤ','ﯗ')
jackkkk7= jackkkk7:gsub('ر','ړُ')
jackkkk7= jackkkk7:gsub('لا','ﻟآ')
jackkkk7= jackkkk7:gsub('ى','ـﮯ')
jackkkk7= jackkkk7:gsub('ة','ة')
jackkkk7= jackkkk7:gsub('و','ۆ')
jackkkk7= jackkkk7:gsub('ز','ژ')
jackkkk7= jackkkk7:gsub('ظ','ﻅ')
jackkkk7= jackkkk7:gsub('q','𝘘')
jackkkk7= jackkkk7:gsub('Q','𝘘')
jackkkk7= jackkkk7:gsub('w','𝘞')
jackkkk7= jackkkk7:gsub('W','𝘞')
jackkkk7= jackkkk7:gsub('e','𝘌')
jackkkk7= jackkkk7:gsub('E','𝘌')
jackkkk7= jackkkk7:gsub('r','𝘙')
jackkkk7= jackkkk7:gsub('R','𝘙')
jackkkk7= jackkkk7:gsub('t','𝘛')
jackkkk7= jackkkk7:gsub('T','𝘛')
jackkkk7= jackkkk7:gsub('y','𝘠')
jackkkk7= jackkkk7:gsub('Y','𝘠')
jackkkk7= jackkkk7:gsub('u','𝘜')
jackkkk7= jackkkk7:gsub('U','𝘜')
jackkkk7= jackkkk7:gsub('i','𝘐')
jackkkk7= jackkkk7:gsub('I','𝘐')
jackkkk7= jackkkk7:gsub('o','𝘖')
jackkkk7= jackkkk7:gsub('O','𝘖')
jackkkk7= jackkkk7:gsub('p','𝘗')
jackkkk7= jackkkk7:gsub('P','𝘗')
jackkkk7= jackkkk7:gsub('a','𝘈')
jackkkk7= jackkkk7:gsub('A','𝘈')
jackkkk7= jackkkk7:gsub('s','𝘚')
jackkkk7= jackkkk7:gsub('S','𝘚')
jackkkk7= jackkkk7:gsub('d','𝘋')
jackkkk7= jackkkk7:gsub('D','𝘋')
jackkkk7= jackkkk7:gsub('f','𝘍')
jackkkk7= jackkkk7:gsub('F','𝘍')
jackkkk7= jackkkk7:gsub('g','𝘎')
jackkkk7= jackkkk7:gsub('G','𝘎')
jackkkk7= jackkkk7:gsub('h','𝘏')
jackkkk7= jackkkk7:gsub('H','𝘏')
jackkkk7= jackkkk7:gsub('j','𝘑')
jackkkk7= jackkkk7:gsub('J','𝘑')
jackkkk7= jackkkk7:gsub('k','𝘒')
jackkkk7= jackkkk7:gsub('K','𝘒')
jackkkk7= jackkkk7:gsub('L','𝘓')
jackkkk7= jackkkk7:gsub('l','𝘓')
jackkkk7= jackkkk7:gsub('z','𝘡')
jackkkk7= jackkkk7:gsub('Z','𝘡')
jackkkk7= jackkkk7:gsub('x','𝘟')
jackkkk7= jackkkk7:gsub('X','𝘟')
jackkkk7= jackkkk7:gsub('c','𝘊')
jackkkk7= jackkkk7:gsub('C','𝘊')
jackkkk7= jackkkk7:gsub('v','𝘝')
jackkkk7= jackkkk7:gsub('V','𝘝')
jackkkk7= jackkkk7:gsub('b','𝘉')
jackkkk7= jackkkk7:gsub('B','𝘉')
jackkkk7= jackkkk7:gsub('n','𝘕')
jackkkk7= jackkkk7:gsub('N','𝘕')
jackkkk7= jackkkk7:gsub('m','𝘔')
jackkkk7= jackkkk7:gsub('M','𝘔')



local jackkkk8= Text:gsub('ض','ض');
jackkkk8= jackkkk8:gsub('ص','صہٰ')
jackkkk8= jackkkk8:gsub('ث','ثہٰـ')
jackkkk8= jackkkk8:gsub('ق','قہٰ')
jackkkk8= jackkkk8:gsub('ف','فہٰ')
jackkkk8= jackkkk8:gsub('غ','غـْ')
jackkkk8= jackkkk8:gsub('ع','ع')
jackkkk8= jackkkk8:gsub('ه','هٰہٰٖ')
jackkkk8= jackkkk8:gsub('خ','خخَـ')
jackkkk8= jackkkk8:gsub('ح','حہٰ')
jackkkk8= jackkkk8:gsub('ج','ججہٰ')
jackkkk8= jackkkk8:gsub('د','دَ')
jackkkk8= jackkkk8:gsub('ذ','ذّ')
jackkkk8= jackkkk8:gsub('ش','ششہٰ')
jackkkk8= jackkkk8:gsub('س','سہٰ')
jackkkk8= jackkkk8:gsub('ي','يٰ')
jackkkk8= jackkkk8:gsub('ب','بٰٰ')
jackkkk8= jackkkk8:gsub('ل','لہٰ')
jackkkk8= jackkkk8:gsub('ا','آ')
jackkkk8= jackkkk8:gsub('ت','تہٰ')
jackkkk8= jackkkk8:gsub('ن','نہٰ')
jackkkk8= jackkkk8:gsub('م','مہٰ')
jackkkk8= jackkkk8:gsub('ك','ككہٰ')
jackkkk8= jackkkk8:gsub('ط','طہٰ')
jackkkk8= jackkkk8:gsub('ئ',' ْئٰ')
jackkkk8= jackkkk8:gsub('ء','ء')
jackkkk8= jackkkk8:gsub('ؤ','ؤؤَ')
jackkkk8= jackkkk8:gsub('ر','رَ')
jackkkk8= jackkkk8:gsub('لا','لہٰا')
jackkkk8= jackkkk8:gsub('ى','ىہٰ')
jackkkk8= jackkkk8:gsub('ة','ة')
jackkkk8= jackkkk8:gsub('و','ہٰو')
jackkkk8= jackkkk8:gsub('ز','ز')
jackkkk8= jackkkk8:gsub('ظ','ظہٰ')
jackkkk8= jackkkk8:gsub('q','𝚀')
jackkkk8= jackkkk8:gsub('Q','𝚀')
jackkkk8= jackkkk8:gsub('w','𝚆')
jackkkk8= jackkkk8:gsub('W','𝚆')
jackkkk8= jackkkk8:gsub('e','𝙴')
jackkkk8= jackkkk8:gsub('E','𝙴')
jackkkk8= jackkkk8:gsub('r','𝚁')
jackkkk8= jackkkk8:gsub('R','𝚁')
jackkkk8= jackkkk8:gsub('t','𝚃')
jackkkk8= jackkkk8:gsub('T','𝚃')
jackkkk8= jackkkk8:gsub('y','𝚈')
jackkkk8= jackkkk8:gsub('Y','𝚈')
jackkkk8= jackkkk8:gsub('u','𝚄')
jackkkk8= jackkkk8:gsub('U','𝚄')
jackkkk8= jackkkk8:gsub('i','𝙸')
jackkkk8= jackkkk8:gsub('I','𝙸')
jackkkk8= jackkkk8:gsub('o','𝙾')
jackkkk8= jackkkk8:gsub('O','𝙾')
jackkkk8= jackkkk8:gsub('p','𝙿')
jackkkk8= jackkkk8:gsub('P','𝙿')
jackkkk8= jackkkk8:gsub('a','𝙰')
jackkkk8= jackkkk8:gsub('A','𝙰')
jackkkk8= jackkkk8:gsub('s','𝚂')
jackkkk8= jackkkk8:gsub('S','𝚂')
jackkkk8= jackkkk8:gsub('d','𝙳')
jackkkk8= jackkkk8:gsub('D','𝙳')
jackkkk8= jackkkk8:gsub('f','𝙵')
jackkkk8= jackkkk8:gsub('F','𝙵')
jackkkk8= jackkkk8:gsub('g','𝙶')
jackkkk8= jackkkk8:gsub('G','𝙶')
jackkkk8= jackkkk8:gsub('h','𝙷')
jackkkk8= jackkkk8:gsub('H','𝙷')
jackkkk8= jackkkk8:gsub('j','𝙹')
jackkkk8= jackkkk8:gsub('J','𝙹')
jackkkk8= jackkkk8:gsub('k','𝙺')
jackkkk8= jackkkk8:gsub('K','𝙺')
jackkkk8= jackkkk8:gsub('L','𝙻')
jackkkk8= jackkkk8:gsub('l','𝙻')
jackkkk8= jackkkk8:gsub('z','𝚉')
jackkkk8= jackkkk8:gsub('Z','𝚉')
jackkkk8= jackkkk8:gsub('x','𝚇')
jackkkk8= jackkkk8:gsub('X','𝚇')
jackkkk8= jackkkk8:gsub('c','𝙲')
jackkkk8= jackkkk8:gsub('C','𝙲')
jackkkk8= jackkkk8:gsub('v','𝚅')
jackkkk8= jackkkk8:gsub('V','𝚅')
jackkkk8= jackkkk8:gsub('b','𝙱')
jackkkk8= jackkkk8:gsub('B','𝙱')
jackkkk8= jackkkk8:gsub('n','𝙽')
jackkkk8= jackkkk8:gsub('N','𝙽')
jackkkk8= jackkkk8:gsub('m','𝙼')
jackkkk8= jackkkk8:gsub('M','𝙼')



local jackkkk9= Text:gsub('ض','ض')
jackkkk9= jackkkk9:gsub('ص','ص')
jackkkk9= jackkkk9:gsub('ث','ث')
jackkkk9= jackkkk9:gsub('ق','قٌ')
jackkkk9= jackkkk9:gsub('ف','فُ')
jackkkk9= jackkkk9:gsub('غ','غ')
jackkkk9= jackkkk9:gsub('ع','عٍ')
jackkkk9= jackkkk9:gsub('ه','هـ')
jackkkk9= jackkkk9:gsub('خ','خـ')
jackkkk9= jackkkk9:gsub('ح','حٍ')
jackkkk9= jackkkk9:gsub('ج','جٍ')
jackkkk9= jackkkk9:gsub('د','دِ')
jackkkk9= jackkkk9:gsub('ذ','ذَ')
jackkkk9= jackkkk9:gsub('ش','شُ')
jackkkk9= jackkkk9:gsub('س','س')
jackkkk9= jackkkk9:gsub('ي','ي')
jackkkk9= jackkkk9:gsub('ب','بَ')
jackkkk9= jackkkk9:gsub('ل','لُِ')
jackkkk9= jackkkk9:gsub('ا','آ')
jackkkk9= jackkkk9:gsub('ت','ت')
jackkkk9= jackkkk9:gsub('ن','ن')
jackkkk9= jackkkk9:gsub('م','م')
jackkkk9= jackkkk9:gsub('ك','ڪ')
jackkkk9= jackkkk9:gsub('ط','طُ')
jackkkk9= jackkkk9:gsub('ئ','ئ ْٰ')
jackkkk9= jackkkk9:gsub('ء','ء')
jackkkk9= jackkkk9:gsub('ؤ','ؤ')
jackkkk9= jackkkk9:gsub('ر','ر')
jackkkk9= jackkkk9:gsub('لا','لُِآ')
jackkkk9= jackkkk9:gsub('ى','ىْ')
jackkkk9= jackkkk9:gsub('ة','ة')
jackkkk9= jackkkk9:gsub('و','وو')
jackkkk9= jackkkk9:gsub('ز','ز')
jackkkk9= jackkkk9:gsub('ظ','ظهُ')
jackkkk9= jackkkk9:gsub('q','ℚ')
jackkkk9= jackkkk9:gsub('Q','ℚ')
jackkkk9= jackkkk9:gsub('w','𝕎')
jackkkk9= jackkkk9:gsub('W','𝕎')
jackkkk9= jackkkk9:gsub('e','𝔼')
jackkkk9= jackkkk9:gsub('E','𝔼')
jackkkk9= jackkkk9:gsub('r','ℝ')
jackkkk9= jackkkk9:gsub('R','ℝ')
jackkkk9= jackkkk9:gsub('t','𝕋')
jackkkk9= jackkkk9:gsub('T','𝕋')
jackkkk9= jackkkk9:gsub('y','𝕐')
jackkkk9= jackkkk9:gsub('Y','𝕐')
jackkkk9= jackkkk9:gsub('u','𝕌')
jackkkk9= jackkkk9:gsub('U','𝕌')
jackkkk9= jackkkk9:gsub('i','𝕀')
jackkkk9= jackkkk9:gsub('I','𝕀')
jackkkk9= jackkkk9:gsub('o','𝕆')
jackkkk9= jackkkk9:gsub('O','𝕆')
jackkkk9= jackkkk9:gsub('p','ℙ')
jackkkk9= jackkkk9:gsub('P','ℙ')
jackkkk9= jackkkk9:gsub('a','𝔸')
jackkkk9= jackkkk9:gsub('A','𝔸')
jackkkk9= jackkkk9:gsub('s','𝕊')
jackkkk9= jackkkk9:gsub('S','𝕊')
jackkkk9= jackkkk9:gsub('d','𝔻')
jackkkk9= jackkkk9:gsub('D','𝔻')
jackkkk9= jackkkk9:gsub('f','𝔽')
jackkkk9= jackkkk9:gsub('F','𝔽')
jackkkk9= jackkkk9:gsub('g','𝔾')
jackkkk9= jackkkk9:gsub('G','𝔾')
jackkkk9= jackkkk9:gsub('h','ℍ')
jackkkk9= jackkkk9:gsub('H','ℍ')
jackkkk9= jackkkk9:gsub('j','𝕁')
jackkkk9= jackkkk9:gsub('J','𝕁')
jackkkk9= jackkkk9:gsub('k','𝕂')
jackkkk9= jackkkk9:gsub('K','𝕂')
jackkkk9= jackkkk9:gsub('L','𝕃')
jackkkk9= jackkkk9:gsub('l','𝕃')
jackkkk9= jackkkk9:gsub('z','ℤ')
jackkkk9= jackkkk9:gsub('Z','ℤ')
jackkkk9= jackkkk9:gsub('x','𝕏')
jackkkk9= jackkkk9:gsub('X','𝕏')
jackkkk9= jackkkk9:gsub('c','ℂ')
jackkkk9= jackkkk9:gsub('C','ℂ')
jackkkk9= jackkkk9:gsub('v','𝕍')
jackkkk9= jackkkk9:gsub('V','𝕍')
jackkkk9= jackkkk9:gsub('b','𝔹')
jackkkk9= jackkkk9:gsub('B','𝔹')
jackkkk9= jackkkk9:gsub('n','ℕ')
jackkkk9= jackkkk9:gsub('N','ℕ')
jackkkk9= jackkkk9:gsub('m','𝕄')
jackkkk9= jackkkk9:gsub('M','𝕄')


local Text_jackkkka = "1- `"..jackkkk..EmojeS[math.random(#EmojeS)]
.."`\n\n2- `"..jackkkk2..EmojeS[math.random(#EmojeS)]
.."`\n\n3- `"..jackkkk3..EmojeS[math.random(#EmojeS)]
.."`\n\n4- `"..jackkkk4..EmojeS[math.random(#EmojeS)]
.."`\n\n5- `"..jackkkk5..EmojeS[math.random(#EmojeS)]
.."`\n\n6- `"..jackkkk6..EmojeS[math.random(#EmojeS)]
.."`\n\n7- `"..jackkkk7..EmojeS[math.random(#EmojeS)]
.."`\n\n8- `"..jackkkk8..Emoje[math.random(#Emoje)]
.."`\n\n9- `"..jackkkk9..Emoje[math.random(#Emoje)]
.."`\n\n10- `"..jackkkk5..Emoje[math.random(#Emoje)]
Text_jackkkka = Text_jackkkka.."`\n\n| اضغـط علـي الاسـم ليتـم النـسخ  \n★"
sendMsg(msg.chat_id_,msg.id_,Text_jackkkka)
return false
end



end

return {
kalia = {
"^(زخرفه)$"
 },
 ikalia = jackkkka,
 dkalia = TextRes,
 }
 
 

--[[
███████▀ │kalia ﹏  @PHP57
│تم تطوير وبرمجة السورس من قبل جاك ✺
│@ UU_YEV
#-------------------------------------------------------------------
]]
